config/routes.rb
Contentbirdme::Application.routes.draw do
  root 'home#index'
  get  'robots.txt'					  => 'home#robots'
  get  'p'                            => 'social_contents#index', as: 'social_contents'
  get  'p/:id'                        => 'social_contents#show',  as: 'social_content'
  get  'permalink/:content_slug'      => 'contents#permalink',    as: 'content_permalink'
  get  '/:section_slug/contents/new'  => 'contents#new',          as: 'new_content'
  post '/:section_slug/contents'      => 'contents#create',       as: 'create_content'
  get  '/:section_slug'               => 'contents#index',        as: 'contents'
  get  '/:section_slug/:content_slug' => 'contents#show',         as: 'content'
end

app/models/cb/me/channel_info.rb
class CB::Me::ChannelInfo

  include CB::Client::Connection

  attr_reader :prefix

  def initialize prefix
    @prefix = prefix
  end

  def get
    conn   = get_connection(url: CREDS_API_URL.to_s)
    conn.basic_auth CREDS_API_URL.user, CREDS_API_URL.password
    perform_request(:get, conn, "/api/channel_info/#{prefix}")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UserFilteringHelper

  protect_from_forgery  with: :exception
  before_action         :restrict_access, :retrieve_requester_info, :set_locale

  rescue_from CB::Client::NotFoundError,  with: :not_found
  rescue_from CB::Client::AppError,       with: :app_error
  rescue_from CB::Client::TimeoutError,   with: :timeout

  def retrieve_requester_info
    success, info = CB::Me::ChannelInfo.new(request.subdomain).get if request.subdomain.present?
    if success
      @channel_id    = info[:result]['key']
      @channel_token = info[:result]['secret_key']
      @channel_type  = info[:result]['type']
    else
      return not_found
    end
  end

private
  def set_locale
    unless Rails.env.test?
      I18n.locale = locale_from_accept_language_header || I18n.default_locale
    end
  end

  def cb_session
    @cb_client ||= CB::Client::Session.new(@channel_id, @channel_token, I18n.locale)
  end

  def not_found
    render 'errors/404', status: 404, layout: 'layouts/error'
  end

  def app_error
    render 'errors/500', status: 500, layout: 'layouts/error'
  end

  def timeout
    render 'errors/500', status: 500, layout: 'layouts/error'
  end

  def locale_from_accept_language_header
    return nil unless request.env['HTTP_ACCEPT_LANGUAGE'].present?
    parsed_locale = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    I18n.available_locales.include?(parsed_locale.to_sym) ? parsed_locale  : nil
  end

  def render_content
    if @channel_type != 'website' && @content['type'] == 'link' && @content['properties']['comment']['value'].blank?
      @direct_redirect_url = @content['properties']['url']['value']
    end
    render :show
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
    result = cb_session.section_contents( params[:section_slug],
                                          context: [:channel, :sections],
                                          page: params[:page] )

    @meta     = result[:meta]
    @contents = result[:result]
    set_context result
  end

  def show
    result = cb_session.section_content( params[:section_slug],
                                         params[:content_slug],
                                         context: [:channel, :sections] )
    @content  = result[:result]
    set_context result
    render_content
  end

  def permalink
    result = cb_session.content(params[:content_slug], context: [:channel, :sections])
    @content  = result[:result]

    set_context result
    render_content
  end

  def new
    result = cb_session.new_section_content( params[:section_slug],
                                                      context: [:channel, :sections, :html] )

    @html_form  = result[:html]
    set_context result
  end

  def create
    result = cb_session.create_section_content( params[:section_slug],
                                                         params[:content],
                                                         context: [:channel, :sections, :html] )
    if result[:result]['errors']
      @html_form  = result[:html]
      set_context result
      render :new
    else
      redirect_to root_path, notice: 'Your content was created'
    end
  end

private

  def set_context result
    @channel  = result[:channel]
    @sections = result[:sections]
    @current_section = nil
    @sections.each do |section|
      (@current_section = section) if section['slug'] == params[:section_slug]
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    return redirect_to(social_contents_path) if @channel_type == 'social'
    result = cb_session.home_contents(context: [:channel, :sections], page: params[:page])
    @contents = result[:result]
    @channel  = result[:channel]
    @sections = result[:sections]
    @meta     = result[:meta]
    @current_section = @sections.first
  end

  def robots
  	render text: (@channel_type == 'website' ? '' : "User-agent: *\nDisallow: /"), layout: false, content_type: "text/plain"
  end

end

app/controllers/social_contents_controller.rb
class SocialContentsController < ApplicationController

  before_action :only_allow_social_channels

  def index
    result = cb_session.contents(page: params[:page], context: [:channel])
    @channel  = result[:channel]
    @meta     = result[:meta]
    @contents = result[:result]
  end

  def show
    result = cb_session.content(params[:id], context: [:channel])
    @channel  = result[:channel]
    @content  = result[:result]
    render_content
  end

private

  def only_allow_social_channels
    redirect_to root_path unless @channel_type == 'social'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper

end

app/helpers/user_filtering_helper.rb
 module UserFilteringHelper

  def restrict_access
    if ip_filter_activated? && !user_ip_allowed?
      ENV['MAINTENANCE_PAGE_URL'].present? ? redirect_to(ENV['MAINTENANCE_PAGE_URL']) : render(text: "IP #{user_ip} Not authorized")
      return
    end
  end

private
  def remote_ip?
    user_ip != "127.0.0.1"
  end

  def user_ip
    request.remote_ip
  end

  def ip_filter_activated?
    IP_FILTERING
  end

  def user_ip_allowed?
    user_ip.present? && IP_WHITELIST.keys.include?(user_ip)
  end
end

app/views/contents/index.html.erb
<section role="main" class="main">
    <h1 class="cb-<%=@current_section['slug']%>-title"><%= @current_section['title'] %></h1>
    <%= render 'shared/section_forewords', section: @current_section %>
    <%= render 'shared/contents', contents: @contents %>
</section>

app/views/contents/new.html.erb
<% content_for :load_script do %>
    H5F.setup($('form'),{invalidClass: "h5fError", requiredClass: "h5fRequired"});
<% end %>
<section class="main">
	<h1 class="cb-<%=@current_section['slug']%>-title"><%= @current_section['title'] %></h1>
	<%= render 'shared/section_forewords', section: @current_section %>
    <article>
    	<%= form_tag create_content_path, method: :post do %>
        	<%= raw @html_form %>
            <%= submit_tag t('.submit') %>
        <% end %>
    </article>
    <footer>
        <%= link_to t('.cancel', section: @current_section['title']), contents_path(@current_section['slug']) %>
    </footer>
</section>

app/views/contents/show.html.erb
<section class="main">
    <%= render 'shared/content', content: @content %>
    <% if @current_section %>
        <footer>
            <%= link_to t('.back_to_section'), contents_path(@current_section['slug']) %>
        </footer>
    <% end %>
</section>

app/views/home/index.html.erb
<section role="main" class="main">
    <%= render 'shared/section_forewords', section: @current_section %>
    <%= render 'shared/contents', contents: @contents %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @channel['name'] %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application",  media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    @channel['css_url'], media: "all", "data-turbolinks-track" => true if @channel['css_url'].present? %>
  <% if @direct_redirect_url.present? %>
      <script>window.location.replace('<%= @direct_redirect_url %>');</script>
  <% end %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :open_graph %>
  <% unless @channel_type == 'website' %>
      <meta name="robots" content="noindex, nofollow">
  <% end %>
</head>
<body class="<%= "section-#{@current_section['slug']}" if @current_section %>">
    <div class="cover"<% if @channel['cover_url'].present? %> style="background: url(<%= @channel['cover_url'] %>) no-repeat center; -webkit-background-size: cover; -o-background-size: cover; background-size: cover;"<% end %>>
        <header>

            <%= link_to image_tag("globals/contentbird.jpg", class: 'logo'), 'http://www.contentbird.com', target: '_blank' %>

            <% if display_sections = (@sections.present? && @sections.size > 1) %>
                <%= link_to '' ,'#', id: 'touchNavLink', class: 'touchNavLink', data: {icon: raw("&#xe009;")} %>
            <% end %>

            <h2 class="channel-name">
                <%= (@channel_type == 'website' || @channel['allow_social_feed']) ? link_to(@channel['name'], root_path) : @channel['name'] %>
            </h2>

            <% if @channel['baseline'].present? %>
                <h3 class="cb-channel-baseline"><%= @channel['baseline'] %></h3>
            <% end %>

        </header>

        <%= (render 'shared/nav', sections: @sections) if display_sections %>

        <footer class="powered">
            <%= t('.powered_by') %>&nbsp;<a href="http://www.contentbird.com" target="_blank">ContentBird</a>.<br />
            <%= t('.tagline') %>
        </footer>
    </div>
    <%= yield %>
    <div id="modal" style="display: none" class="modal"></div>
    <div class="modal-overlay"></div>
    <%= render "cb-render/js_templates" %>
    <script>
        $(document).ready(function() {
            $( "#touchNavLink" ).click(function(e) {
              $( "#mainNav" ).toggleClass('opened');
              e.preventDefault();
            });
            cb.decorateModal();
            cb.decorateGalleries();
            cb.decorateUrls();
            cb.decorateMarkdownLinks();
          <%= yield :load_script %>
        });
    </script>
    <%= render "cb-render/tracking/piwik" %>
</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Contentbird.me</title>
	<%= csrf_meta_tags %>
	<style>
		html {
		    font-family: "Lucida Grande", "Lucida Sans Unicode", Helvetica, Arial, Verdana, sans-serif;
			font-size: 1.125rem;
			font-size: 100%;
		}
		body {
			height: 100%;
		  	padding-top: 15%;
		  	text-align: center;
		}
		a, a:active {
			text-decoration: none;
			color: #1122cc;
		}
		a:hover {
			opacity: 0.8;
		}
		p {
			line-height: 1.125rem;
		}
	</style>
</head>
<body>
    <%= yield %>
</body>
</html>

app/views/shared/_content.html.erb
<% content_for :open_graph do %>
    <meta property="og:title"       content="<%= content['title'] %>" />
    <meta property="og:site_name"   content="ContentBird"             />
    <% first_text  = content['first_text']  ? content['properties'][content['first_text']]['value'].to_s : content['title'] %>
    <meta property="og:description" content="<%= truncate(first_text, length: 100, separator: ' ') %>"        />
    <% if content['thumbnail'].present? %>
    	<meta property="og:image" content="<%= 'http:' + content['thumbnail']%>" />
    <% end %>
<% end %>

<article class="cb-content-detail <%= "cb-type-#{content['type']}" %>">
    <h2 class="cb-content-title"><%= content['title'] %></h2>
    <% content['properties'].each do |prop_name, property| %>
        <%= display_content_property prop_name, property, display_label: (property['type']!='memo') %>
    <% end %>
    <p class= "notabene"><%= t('shared.publication_time', time: l(Time.parse(content['published_at']))) %></p>
</article>

app/views/shared/_contents.html.erb
<% if contents.size == 1 %>
    <%= render 'shared/content', content: contents.first %>
<% else %>
    <% contents.each do |content| %>
        <% first_image = content['first_image'] ? content['properties'][content['first_image']] : nil %>
        <% first_text  = content['first_text']  ? content['properties'][content['first_text']]  : nil %>
        <article class="box cb-content-summary <%= "cb-type-#{content['type']}" %>">
            <header class="box-hd">
                <h2 class="cb-content-title">
                    <%= link_to content['title'], content_path(@current_section['slug'], content['slug']) %>
                </h2>
            </header>
            <div class="box-bd">
                <% if first_image %>
                    <%= display_content_property(content['first_image'], first_image, wrapper_class: "box--md", summary: true) %>
                <% end %>
                <% if first_text %>
                    <%= display_content_property content['first_text'], first_text, {display_label: (first_text['type']!='memo'), wrapper_class: "box--ct"} %>
                <% end %>
                <span class="notabene"><%= t('shared.publication_time', time: l(Time.parse(content['published_at']))) %></span>
            </div>
        </article>
    <% end %>
	<footer>
		<%= render(partial: 'shared/pagination',
			       locals: { current_page: @meta['current_page'],
							 last_page: @meta['total_pages']      }) if @meta %>
	</footer>
<% end %>

app/views/shared/_nav.html.erb
<nav id="mainNav" class="mainNav <%= 'nav-large' if sections.size > 6 %>" role="navigation">
    <ul>
        <% sections.each do |section| %>
            <% section_link = (section['mode'] == 'display' ? contents_path(section['slug']) : new_content_path(section['slug'])) %>
            <li><%= link_to section['title'], section_link, class: (params[:section_slug] == section['slug'] ? 'selected' : '') %></li>
        <% end %>
    </ul>
</nav>

app/views/shared/_pagination.html.erb
<% if last_page && last_page > 1 %>
    <div class="cb-pagination">
    	<% (1..last_page).each do |page_number| %>
    		<% if page_number == current_page %>
    			<strong class="cb-pagination-current"><%= page_number %><strong>&nbsp;
    		<% else %>
    			<%= link_to page_number, (request.query_string.present? ? request.original_fullpath+"&page=#{page_number}" : request.original_fullpath + "?page=#{page_number}") %>
    		<% end %>
    	<% end %>
    </div>
<% end %>

app/views/shared/_section_forewords.html.erb
<% if section['forewords'].present? %>
	<p class="cb-<%=section['slug']%>-forewords"><%= simple_format(section['forewords']) %></p>
<% end %>

app/views/social_contents/index.html.erb
<section role="main" class="main">
    <% @contents.each do |content| %>
        <% first_image = content['first_image'] ? content['properties'][content['first_image']] : nil %>
        <% first_text  = content['first_text']  ? content['properties'][content['first_text']]  : nil %>
        <article class="box">
        	<header class="box-hd">
        		<h2 class="cb-content-title"><%= link_to content['title'], social_content_path(content['slug']) %></h2>
        	</header>
            <div class="box-bd">
            	<% if first_image %>
                    <%= display_content_property(content['first_image'], first_image, wrapper_class: "box--md") %>
                <% end %>
                <% if first_text %>
                    <%= display_content_property content['first_text'], first_text, {display_label: (first_text['type']!='memo'), wrapper_class: "box--ct"} %>
                <% end %>
            </div>
        </article>
    <% end %>
</section>

app/views/social_contents/show.html.erb
<section role="main" class="main">
    <%= render 'shared/content', content: @content %>
    <footer>
        <%= (link_to t('.back_to_section'), social_contents_path) if @channel['allow_social_feed'] %>
    </footer>
</section>